### ISSUE TITLE
Implement PATCH API calls

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#248] opened 2019-08-01 15:37 UTC
REST API calls here are currently restricted to GET, POST, PUT, DELETE.
We need to implement PATCH as discussed [here](https://github.com/HumanBrainProject/hbp-validation-framework/issues/241#issuecomment-517338912).

**Comment by apdavison** [comment] 2020-06-16 13:19
effectively a duplicate of #181

**Closed by apdavison** 2020-06-16 13:19 UTC
Labels: REST API v1, REST API v2, duplicate
